### ISSUE TITLE
Activation sur le reseau

### ISSUE THREAD

**Issue by sebastienserre** [geoffreycrofte/juiz-social-post-sharer#13]
Bonjour,
Dans le cadre d'un multisite. l'activation au niveau du réseau ne fonctionne pas completement, la page admin est cassée
https://www.dropbox.com/s/92bvkunyaz94s2w/juice-social.jpg

**Comment by geoffreycrofte** [comment]
Hello Sebastien,
Je n'ai toujours pas eu l'occasion de tester en multisite, j'ai mis un peu de côté le développement de mes plugins faute de temps.
Aucune date prévue pour le moment, je te ping quand c'est édité :)

**Comment by geoffreycrofte** [comment]
Hello,
Un peu de temps pour répondre mais le développement a avancé.
Cela devraiet désormais fonctionner avec la version 2.0.0 qui arrive bientôt.
Merci à toi.
