### ISSUE TITLE
[not serious] Fix deprecated functions in admin.inc.php

### ISSUE THREAD

**Issue by plethorahil** [geoffreycrofte/juiz-social-post-sharer#16]
Been getting this warnings when enabled debug mode.

_juiz-social-post-sharer\admin\jsps-admin.inc.php on line 192
juiz-social-post-sharer\admin\jsps-admin.inc.php on line 195
juiz-social-post-sharer\admin\jsps-admin.inc.php on line 201
juiz-social-post-sharer\admin\jsps-admin.inc.php on line 211_

**Comment by geoffreycrofte** [comment]
Thanks for your feedback.
The issue comes from this `function(){ ''; return "";}`

In the 2.0.0 coming soon I use `__return_empty_string` builin function to avoid anonymous function.

Thanks for pointing this out.
