### ISSUE TITLE
Support WPML and WP Translate for mail button translations.

### ISSUE THREAD

**Issue by geoffreycrofte** [geoffreycrofte/juiz-social-post-sharer#41]
Make Custom Strings with placeholders translatable

**Comment by sebastienserre** [comment]
If you use a wpml-config.xml you should be also compatible with Polylang (https://polylang.pro/doc/the-wpml-config-xml-file/)

**Comment by geoffreycrofte** [comment]
Thank you so much for your help @sebastienserre
